language: php

php:
 - 5.5
 - 5.6
 - 7.0
 - hhvm
 - hhvm-nightly
 - nightly

script:
 - ./vendor/bin/phpunit --configuration=phpunit.travis.xml

matrix:
 allow_failures:
  - php: hhvm-nightly
  - php: nightly
addons:
 code_climate:
  repo_token:
   secure: "hDXxhsoBWhQVPqtV5hOVpfXQd/C96TyESTC/M7/AbaRWka77fssxn18UGqzw8o3xhw+y9/JzQOgjX8k3nrdsyU5lE6DZxCZ+eFC0xnt1FU1PJf9SHlCPNDqkRmNJ7D8dB5i0qCZfVm2ND73Vvad2PZyLa66snK3bwlpeMuvZJaI="

after_script:
 - ./vendor/bin/test-reporter --stdout > codeclimate.json
 - 'curl -X POST -d @codeclimate.json -H "Content-Type: application/json" -H "User-Agent: Code Climate (PHP Test Reporter v1.0.1-dev)"  https://codeclimate.com/test_reports'
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
