language: php

php:
 - 5.6
 - 7.0
 - hhvm
 - nightly

script:
 - ./vendor/bin/phpunit --configuration=phpunit.travis.xml

matrix:
 allow_failures:
  - php: nightly
addons:
 code_climate:
  repo_token:
    secure: "GFM70GBUuDZ3KUwqgPwXTFdXm6c/4SWF/vNC99YpmENF6Lq6dFez9zeh+kVViFAzjgFIueW1TAsSnJSYCdS3Reka9jN8NXSExFAR0MW/zxLdfpaefZxxvTwy1QwFQO+WxSDTdcFFpJAvR5xVClz7Wnm/mLEhSqpKV1veBy1fxUTeoVd6StUYkFeJgWMzAQqMjQlrgpEISgbTidZIflVbkmZ46sTj/RhOfaSOPK/CMSRl0YNW58yngnM4aH/MmwnPj2oacDLAwqyaTJxD2VGTvYtrefQ+riB9nnukgNNFWwCFhrFtf4U4o6sAR1bdWVre4lWuyhiDc3eO9u8tMIvftf7mKAjYwEf8AwKQ8jXzRIUiAJSDu3hKzBDRINnIDGrlTlKkhKRVSFr9y8krfhHDUhehRoGSBk5FGRHZ78OYUY1SbLNyzM17CocfyvMkJCBmkkjKl62V8gkXzae/xbqZ0TSQn4JBPt+9AXf377XE22ZVeBwDiy+qT2NYG64gU/xzEhWUlegqd+8/xLvaDtvd+vjyOBhWGCrbYpUjj9OrmTfCCMbJa5Rew+sy9k/DTQiSj5RHeSkZqUJrcNJDKkyP/OftMMmj+L8GsYW3AmI4McWr97e1JD71RtoS72SyKqYvnguIHxB3lPFNikxZhY8ypd2EeiOHosgo1NAseE9Dtlc="

before_script:
 - ./.travis.install.sh

after_script:
 - ./vendor/bin/test-reporter
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
